name: Update M3U8 Playlist

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install node-fetch@2 winston

      - name: Run Script
        run: node run.js

      - name: Configure git user
        run: |
          git config --global user.name 'lalitakatariya4321'
          git config --global user.email "${{ secrets.USER_EMAIL }}"

      - name: Commit and Push Changes
        run: |
          git add ts.m3u
          git commit -m 'Update M3U8 playlist'
          git push origin ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.BINDAAS }}

      - name: Trigger Second Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          --data '{"event_type":"trigger-jekyll-build"}'
